Feature/basket
xnagpa/react-repeat pull request #3
Opened 2019-06-04 17:20 UTC by xnagpa

2019-06-04 19:45 UTC, index01d requested changes

2019-06-04 19:45 UTC, index01d commented on components/CatalogPage.js
> +    increaseCounter(e) {
ошибка здесь вообще в выборе достаточного уровня абстракции, идея же в том, чтобы дать возможность "добавить в корзину" (высокоуровневое определение), а не увеличить счетчик (деталь реализации). В компонентах нужно стараться избегать слишком низкоуровневых определений.

Положим, что здесь у нас будет метод `addToCart(product, amount)`, то есть метод для добавления продукта в корзину

2019-06-04 19:45 UTC, index01d commented on components/CatalogPage.js
> +      this.state = { count: 0 };
не является состоянием страницы каталога. нужно отдельно выделить CartContainer и обернуть в него CatalogPage, например. А вот уже у CartContainer будет состояние со списком продуктов `this.state = { entries: [...] }` (несмотря на то что на кнопке по заданию должно быть только количество товаров, в состоянии я рекомендую хранить настоящий список).

2019-06-04 19:45 UTC, index01d commented on components/ProductCard.js
> +    // Это норм или говно?
это очень нехорошо, когда презентационный компонент карточки наделен знанием о деталях реализации корзины

2019-06-04 19:45 UTC, index01d commented on components/ProductCard.js
> +          <BasketContext.Consumer>
чтобы этого избежать нужно весь код, вместе с Consumer'ом унести в AddToBasket. Тогда здесь останется 
`<AddToBasket product={this.props.product} />` или this.props.

2019-06-04 19:45 UTC, index01d commented on components/AddToBasket.js
> +class AddToBasket extends Component {
здесь можно добавить состояние `this.state.count`, которое менять на onChange в поле счетчика, тогда в `this.handler` можно будет использовать текущее значение из поля ввода (см комментарии к ProductCard)

2019-06-04 19:45 UTC, index01d commented on components/CatalogPage.js
> +    increaseCounter(e) {
Также, в контейнере корзины не стоит обрабатывать события дочерних элементов (е). Само событие нужно обработать в презентационном компоненте, а уже там в обработчике вызвать метод из контекста `(e) => { context.addToCart(this.props.product, this.state.amount); }`

2019-06-20 07:16 UTC, index01d requested changes

2019-06-20 07:16 UTC, index01d commented on components/AppContainer.js
> +      this.state = {
по-хорошему корзину и её состояние нужно выделить в отдельный CartContainer и обернуть в него приложение

2019-06-20 07:16 UTC, index01d commented on components/Basket.js
> +    this.props.basket.forEach((product) => {
уместнее использовать .map

2019-06-20 07:16 UTC, index01d commented on components/Catalog.js
> +          product={product}/>);
деструктурирование тогда нужно производить в карточке, а здесь передавать только продукт;
уместнее использовать map

2019-06-20 10:32 UTC, xnagpa commented on components/AppContainer.js
> +      this.state = {
done

2019-06-20 10:34 UTC, xnagpa commented on components/Basket.js
> +    this.props.basket.forEach((product) => {
Поправлено

2019-06-20 10:41 UTC, xnagpa commented on components/Catalog.js
> +          product={product}/>);
Поправил

2019-06-20 11:44 UTC, index01d approved these changes

2019-06-20 12:28 UTC, merged